{
 "title": "MongoDB WiredTiger Details",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "replset",
    "query": {
     "query": "label_values(mongodb_mongod_replset_my_state{}, set)"
    }
   },
   {
    "name": "node_name",
    "query": {
     "query": "label_values(mongodb_mongod_replset_my_state{set=~\"$replset\",}, node_name)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(mongodb_mongod_replset_my_state{set=~\"$replset\",}, app_kubernetes_io_instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "WiredTiger Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "WiredTiger Cache Activity",
     "type": "graph",
     "description": "Data volume transfered per second between the WT cache and data files. Writes out always imply disk; Reads are often from OS filebuffer cache already in RAM, but disk if not.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "avg by (node_name, type) (rate(mongodb_mongod_wiredtiger_cache_bytes_total{app_kubernetes_io_instance=~\"$instance\", node_name=~\"$node_name\"}[$interval]) or irate(mongodb_mongod_wiredtiger_cache_bytes_total{app_kubernetes_io_instance=~\"$instance\", node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "{{node_name}} - {{type}}"
      }
     ]
    },
    {
     "title": "WiredTiger Cache Eviction",
     "type": "timeseries",
     "description": "Least-recently used pages being evicted due to WT cache becoming full.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (node_name,type) (rate(mongodb_mongod_wiredtiger_cache_evicted_total{ node_name=~\"$node_name\"}[$interval]) or irate(mongodb_mongod_wiredtiger_cache_evicted_total{ node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "{{node_name}} - {{type}}"
      }
     ]
    },
    {
     "title": "WiredTiger Cache Capacity",
     "type": "graph",
     "description": "Configured max and current size of the WT cache.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg by (node_name) (max_over_time(mongodb_mongod_wiredtiger_cache_max_bytes{ node_name=~\"$node_name\"}[$interval]) or\nmax_over_time(mongodb_mongod_wiredtiger_cache_max_bytes{node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "{{node_name}} Max"
      },
      {
       "expr": "avg by (node_name) (max_over_time(mongodb_mongod_wiredtiger_cache_bytes{ node_name=~\"$node_name\"}[$interval]) or\nmax_over_time(mongodb_mongod_wiredtiger_cache_bytes{node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "{{node_name}} Used"
      }
     ]
    },
    {
     "title": "WiredTiger Cache Pages",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (node_name, type) (max_over_time(mongodb_mongod_wiredtiger_cache_pages{ node_name=~\"$node_name\"}[$interval]) or\nmax_over_time(mongodb_mongod_wiredtiger_cache_pages{ node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "{{node_name}} {{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "MongoDB WiredTiger Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "WiredTiger Transactions (5m)",
     "type": "timeseries",
     "description": "WiredTiger internal transactions",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(mongodb_mongod_wiredtiger_transactions_total{node_name=~\"$node_name\",app_kubernetes_io_instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{kubernetes_pod_name}} - {{type}}"
      }
     ]
    },
    {
     "title": "WiredTiger Sessions/Cursors",
     "type": "timeseries",
     "description": "Internal WT storage engine cursors and sessions currently open",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (node_name) (max_over_time(mongodb_mongod_wiredtiger_session_open_cursors_total{ node_name=~\"$node_name\"}[$interval]) or\nmax_over_time(mongodb_mongod_wiredtiger_session_open_cursors_total{ node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Cursors Opened - {{node_name}}"
      },
      {
       "expr": "avg by (node_name) (max_over_time(mongodb_mongod_wiredtiger_session_open_sessions_total{ node_name=~\"$node_name\"}[$interval]) or\nmax_over_time(mongodb_mongod_wiredtiger_session_open_sessions_total{ node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Sessions Opened - {{node_name}}"
      }
     ]
    },
    {
     "title": "Queued Operations",
     "type": "timeseries",
     "description": "Operations queued due to a lock.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (node_name,type) (max_over_time(mongodb_mongod_global_lock_current_queue{ node_name=~\"$node_name\"}[$interval]) or\nmax_over_time(mongodb_mongod_global_lock_current_queue{ node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "{{node_name}} - {{type}}"
      }
     ]
    },
    {
     "title": "WiredTiger Block Activity",
     "type": "timeseries",
     "description": "Data volume handled by the WT block manager per second",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "avg by (node_name,type) (rate(mongodb_mongod_wiredtiger_blockmanager_bytes_total{ node_name=~\"$node_name\"}[$interval]) or irate(mongodb_mongod_wiredtiger_blockmanager_bytes_total{node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "{{node_name}} bytes {{type}}"
      }
     ]
    },
    {
     "title": "WiredTiger Log Activity",
     "type": "graph",
     "description": "Data volume moved per second in WT internal write-ahead log.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "avg by (node_name,type) (rate(mongodb_mongod_wiredtiger_log_bytes_total{node_name=~\"$node_name\"}[$interval]) or irate(mongodb_mongod_wiredtiger_log_bytes_total{node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "{{node_name}} {{type}}"
      }
     ]
    },
    {
     "title": "WiredTiger Concurrency Tickets Available",
     "type": "timeseries",
     "description": "A WT 'ticket' is assigned out for every operation running simultaneously in the WT storage engine. \"Available\" = hardcoded high value - \"Out\".",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (node_name,type) (max_over_time(mongodb_mongod_wiredtiger_concurrent_transactions_available_tickets{ node_name=~\"$node_name\"}[$interval]) or\nmax_over_time(mongodb_mongod_wiredtiger_concurrent_transactions_available_tickets{node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "{{node_name}} - {{type}}"
      }
     ]
    },
    {
     "title": "Document Changes",
     "type": "timeseries",
     "description": "Mixed metrics: Docs per second inserted, updated, deleted or returned on any type of node (primary or secondary); + replicated write Ops/sec; + TTL deletes per second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "avg by (node_name,state) (rate(mongodb_mongod_metrics_document_total{node_name=~\"$node_name\"}[$interval]) or irate(mongodb_mongod_metrics_document_total{node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "{{node_name}} {{state}}"
      }
     ]
    },
    {
     "title": "WiredTiger Checkpoint Time",
     "type": "timeseries",
     "description": "The time spent in WT checkpoint phase. Warning: This calculation averages the cyclical event (default: 1 min) execution to a per-second value.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by (node_name) (rate(mongodb_mongod_wiredtiger_transactions_checkpoint_milliseconds_total{ node_name=~\"$node_name\"}[$interval]) or irate(mongodb_mongod_wiredtiger_transactions_checkpoint_milliseconds_total{ node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "{{node_name}} current"
      },
      {
       "expr": "avg by (node_name, type) (max_over_time(mongodb_mongod_wiredtiger_transactions_checkpoint_milliseconds{ node_name=~\"$node_name\"}[$interval]) or\nmax_over_time(mongodb_mongod_wiredtiger_transactions_checkpoint_milliseconds{ node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "{{node_name}} {{type}}"
      }
     ]
    },
    {
     "title": "Page Faults",
     "type": "timeseries",
     "description": "Unix or Window memory page faults. Not necessarily from mongodb.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (node_name) (rate(mongodb_extra_info_page_faults_total{ node_name=~\"$node_name\"}[$interval]) or irate(mongodb_extra_info_page_faults_total{node_name=~\"$node_name\"}[5m]) \n)",
       "legendFormat": "{{node_name}} Page Faults"
      }
     ]
    },
    {
     "title": "WiredTiger Log Operations",
     "type": "graph",
     "description": "WT internal write-ahead log operations.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "avg by (node_name,type) (rate(mongodb_mongod_wiredtiger_log_operations_total{node_name=~\"$node_name\"}[$interval]) or irate(mongodb_mongod_wiredtiger_log_operations_total{node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "{{node_name }} {{type}}"
      }
     ]
    },
    {
     "title": "WiredTiger Log Records",
     "type": "graph",
     "description": "Number of records appended per second in WT internal log.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "avg by (node_name,type) (rate(mongodb_mongod_wiredtiger_log_records_total{node_name=~\"$node_name\"}[$interval]) or irate(mongodb_mongod_wiredtiger_log_records_total{node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "{{node_name}} {{type}}"
      }
     ]
    }
   ]
  },
  { "title": "MongoDB Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "MongoDB Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (app_kubernetes_io_instance) (mongodb_instance_uptime_seconds{app_kubernetes_io_instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 5, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(mongodb_mongod_op_latencies_ops_total{ node_name=~\"$node_name\",type!=\"command\"}[$interval]) or irate(mongodb_mongod_op_latencies_ops_total{node_name=~\"$node_name\",type!=\"command\"}[5m]))"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (node_name) (rate(mongodb_mongod_op_latencies_latency_total{node_name=~\"$node_name\",type=\"command\"}[$interval]) / (rate(mongodb_mongod_op_latencies_ops_total{node_name=~\"$node_name\",type=\"command\"}[$interval]) > 0) or\nirate(mongodb_mongod_op_latencies_latency_total{node_name=~\"$node_name\",type=\"command\"}[5m]) / (irate(mongodb_mongod_op_latencies_ops_total{node_name=~\"$node_name\",type=\"command\"}[5m]) > 0))",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "description": "This shows the number of active connections on the server. Keep in mind the hard limit on the maximum number of connections set by your distribution.\n\nYou can read more about the [connection numbers](https://docs.mongodb.com/manual/administration/analyzing-mongodb-performance/#number-of-connections).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (node_name) (max_over_time(mongodb_connections{node_name=~\"$node_name\", state=\"current\"}[$interval]) or \nmax_over_time(mongodb_connections{node_name=~\"$node_name\", state=\"current\"}[5m]))",
     "legendFormat": "{{node_name }}"
    }
   ]
  },
  {
   "title": "Cursors",
   "type": "timeseries",
   "description": "This shows the number of open cursors for each shard in the cluster. A cursor in MongoDB is a pointer to the result of a given query that can be iterated over. By default a cursor times out after 10 minutes.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (node_name,state) (max_over_time(mongodb_mongod_metrics_cursor_open{ node_name=~\"$node_name\"}[$interval]) or\nmax_over_time(mongodb_mongod_metrics_cursor_open{node_name=~\"$node_name\"}[5m]) )",
     "legendFormat": "{{node_name}} {{state}}"
    }
   ]
  }
 ]
}