{
 "title": "MongoDB ReplSet Summary",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "replset_instance",
    "query": {
     "query": "label_values(mongodb_instance_uptime_seconds, app_kubernetes_io_instance)"
    }
   },
   {
    "name": "replset",
    "query": {
     "query": "label_values(mongodb_mongod_replset_my_state{app_kubernetes_io_instance=~\"$replset_instance\"}, set)"
    }
   },
   {
    "name": "node_name",
    "query": {
     "query": "label_values(mongodb_mongod_replset_my_state{set=~\"$replset\"}, node_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ReplSet Members",
   "type": "stat",
   "description": "This shows how many members are configured in the replica set.",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(mongodb_mongod_replset_number_of_members{set=~\"$replset\"})"
    }
   ]
  },
  {
   "title": "ReplSet Last Election",
   "type": "stat",
   "description": "This shows the time since the last election.",
   "gridPos": { "h": 3, "w": 9, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(mongodb_mongod_replset_member_election_date{set=~\"$replset\"})"
    }
   ]
  },
  {
   "title": "Avg ReplSet Lag",
   "type": "stat",
   "description": "This panel shows how far behind in replication this member is if it is a secondary. This number may be high it the instance is running as a delayed secondary member.",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (set) (max_over_time(mongodb_mongod_replset_member_replication_lag{ set=~\"$replset\"}[$interval]))"
    }
   ]
  },
  {
   "title": "ReplSet States",
   "type": "natel-discrete-panel",
   "description": "ReplSet statuses during the select time range.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "group by(name, state) (mongodb_mongod_replset_member_health{set=~\"$replset\"})",
     "legendFormat": "{{name}} - {{state}}"
    }
   ]
  },
  { "title": "CPU Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "CPU Usage - Request",
   "type": "timeseries",
   "description": "The CPU time is measured in clock ticks or seconds. It is useful to measure CPU time as a percentage of the CPU's capacity, which is called the CPU usage.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "eagle_pod_container_resource_usage_cpu_cores{container=\"mongodb\", pod=~\"${replset_instance}-[0-9]+\"} / eagle_pod_container_resource_requests_cpu_cores{container=\"mongodb\", pod=~\"${replset_instance}-[0-9]+\"}",
     "legendFormat": "{{pod }}"
    }
   ]
  },
  {
   "title": "CPU Usage - Limit",
   "type": "timeseries",
   "description": "The CPU time is measured in clock ticks or seconds. It is useful to measure CPU time as a percentage of the CPU's capacity, which is called the CPU usage.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "eagle_pod_container_resource_usage_cpu_cores{container=\"mongodb\", pod=~\"${replset_instance}-[0-9]+\"} / eagle_pod_container_resource_limits_cpu_cores{container=\"mongodb\", pod=~\"${replset_instance}-[0-9]+\"}",
     "legendFormat": "{{pod }}"
    }
   ]
  },
  {
   "title": "CPU Usage - Cores",
   "type": "timeseries",
   "description": "The CPU time is measured in clock ticks or seconds. It is useful to measure CPU time as a percentage of the CPU's capacity, which is called the CPU usage.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "eagle_pod_container_resource_usage_cpu_cores{container=\"mongodb\", pod=~\"${replset_instance}-[0-9]+\"} ",
     "legendFormat": "{{pod }}"
    }
   ]
  },
  {
   "title": "CPU Throttling",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_periods_total{container=\"mongodb\", pod=~\"${replset_instance}-[0-9]+\"}[5m])",
     "legendFormat": "{{pod }}"
    }
   ]
  },
  { "title": "Memory Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Memory Usage Percent Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "eagle_pod_container_resource_usage_memory_bytes{container=\"mongodb\", pod=~\"${replset_instance}-[0-9]+\"} / eagle_pod_container_resource_requests_memory_bytes{ container=\"mongodb\", pod=~\"${replset_instance}-[0-9]+\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage Percent Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "eagle_pod_container_resource_usage_memory_bytes{container=\"mongodb\", pod=~\"${replset_instance}-[0-9]+\"} / eagle_pod_container_resource_limits_memory_bytes{ container=\"mongodb\", pod=~\"${replset_instance}-[0-9]+\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "eagle_pod_container_resource_usage_memory_bytes{container=\"mongodb\", pod=~\"${replset_instance}-[0-9]+\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Fail Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(container_memory_failcnt{container=\"mongodb\", pod=~\"${replset_instance}-[0-9]+\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "MongoDB Services Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Services Details",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "max by(node_name) (mongodb_instance_uptime_seconds{app_kubernetes_io_instance=~\"$replset_instance\"})",
     "legendFormat": "{{node_name}} | Uptime"
    },
    {
     "expr": "sum by (node_name)  (rate(mongodb_op_counters_total{app_kubernetes_io_instance=~\"$replset_instance\",type!=\"command\"}[$interval]) or irate(mongodb_op_counters_total{app_kubernetes_io_instance=~\"$replset_instance\",type!=\"command\"}[5m]))",
     "legendFormat": "{{node_name}} | QPS"
    },
    {
     "expr": "avg by (node_name) (rate(mongodb_mongod_op_latencies_latency_total{app_kubernetes_io_instance=~\"$replset_instance\",type=\"command\"}[$interval]) / (rate(mongodb_mongod_op_latencies_ops_total{app_kubernetes_io_instance=~\"$replset_instance\",type=\"command\"}[$interval]) > 0) or\nirate(mongodb_mongod_op_latencies_latency_total{app_kubernetes_io_instance=~\"$replset_instance\",type=\"command\"}[5m]) / (irate(mongodb_mongod_op_latencies_ops_total{app_kubernetes_io_instance=~\"$replset_instance\",type=\"command\"}[5m]) > 0))",
     "legendFormat": "{{node_name}} | Latency"
    },
    {
     "expr": "avg by (node_name) (max_over_time(mongodb_mongod_connections{app_kubernetes_io_instance=~\"$replset_instance\", state=\"current\"}[$interval]) or \nmax_over_time(mongodb_mongod_connections{app_kubernetes_io_instance=~\"$replset_instance\", state=\"current\"}[5m]) or\nmax_over_time(mongodb_mongos_connections{app_kubernetes_io_instance=~\"$replset_instance\", state=\"current\"}[$interval]) or\nmax_over_time(mongodb_mongos_connections{app_kubernetes_io_instance=~\"$replset_instance\", state=\"current\"}[5m]) or\nmax_over_time(mongodb_connections{app_kubernetes_io_instance=~\"$replset_instance\", state=\"current\"}[$interval]) or\nmax_over_time(mongodb_connections{app_kubernetes_io_instance=~\"$replset_instance\", state=\"current\"}[5m]))",
     "legendFormat": "{{node_name}} | Connections"
    },
    {
     "expr": "avg by (node_name) (max_over_time(mongodb_mongod_metrics_cursor_open{app_kubernetes_io_instance=~\"$replset_instance\",state=\"total\"}[$interval]) or\nmax_over_time(mongodb_mongod_metrics_cursor_open{app_kubernetes_io_instance=~\"$replset_instance\",state=\"total\"}[5m]) or\nmax_over_time(mongodb_mongod_cursors{app_kubernetes_io_instance=~\"$replset_instance\",state=\"total\"}[$interval]) or\nmax_over_time(mongodb_mongod_cursors{app_kubernetes_io_instance=~\"$replset_instance\",state=\"total\"}[5m]) or\nmax_over_time(mongodb_mongos_metrics_cursor_open{app_kubernetes_io_instance=~\"$replset_instance\",state=\"total\"}[$interval]) or \nmax_over_time(mongodb_mongos_metrics_cursor_open{app_kubernetes_io_instance=~\"$replset_instance\",state=\"total\"}[5m]) or\nmax_over_time(mongodb_mongos_cursors{app_kubernetes_io_instance=~\"$replset_instance\",state=\"total\"}[$interval]) or\nmax_over_time(mongodb_mongos_cursors{app_kubernetes_io_instance=~\"$replset_instance\",state=\"total\"}[5m]))",
     "legendFormat": "{{node_name}} | Cursors "
    }
   ]
  },
  {
   "title": "Latency Detail",
   "type": "timeseries",
   "description": "Average latency of operations (classified by read, write, or (other) command).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg by (node_name,type) (rate(mongodb_mongod_op_latencies_latency_total{node_name=~\"$node_name\"}[$interval]) / (rate(mongodb_mongod_op_latencies_ops_total{node_name=~\"$node_name\"}[$interval]) > 0) or irate(mongodb_mongod_op_latencies_latency_total{node_name=~\"$node_name\"}[5m]) / (irate(mongodb_mongod_op_latencies_ops_total{node_name=~\"$node_name\"}[5m]) > 0))\n",
     "legendFormat": "{{node_name}} - {{ type }}"
    }
   ]
  },
  {
   "title": "Document Operations",
   "type": "timeseries",
   "description": "Docs per second inserted, updated, deleted or returned. (N.b. not 1-to-1 with operation counts.)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (node_name,state) (rate(mongodb_mongod_metrics_document_total{node_name=~\"$node_name\"}[$interval]) or \nirate(mongodb_mongod_metrics_document_total{node_name=~\"$node_name\"}[5m]))",
     "legendFormat": "{{node_name}} - {{state}}"
    }
   ]
  },
  {
   "title": "Free Cache",
   "type": "timeseries",
   "description": "MongoDB keeps most recently used data in RAM. If you have created indexes for your queries and your working data set fits in RAM, MongoDB serves all queries from memory.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (node_name, cache) (mongodb_tcmalloc_cache_bytes{node_name=~\"$node_name\",type=\"free\"})",
     "legendFormat": "Free {{cache}}"
    }
   ]
  },
  { "title": "Replication Lag", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Replication Lag",
   "type": "timeseries",
   "description": "MongoDB replication lag occurs when the secondary node cannot replicate data fast enough to keep up with the rate that data is being written to the primary node. It could be caused by something as simple as network latency, packet loss within your network, or a routing issue.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (name) (mongodb_mongod_replset_member_replication_lag{set=\"$replset\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Replication Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (kubernetes_pod_name,app_kubernetes_io_instance,type) (rate(mongodb_op_counters_repl_total{kubernetes_pod_name=~\"$node_name\"}[$interval]) or irate(mongodb_op_counters_repl_total{kubernetes_pod_name=~\"$node_name\"}[5m]))",
     "legendFormat": "{{kubernetes_pod_name}} - {{type}}"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "timeseries",
   "description": "Operations are classified by legacy wire protocol type (insert, update, and delete only).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (kubernetes_pod_name,type) (rate(mongodb_op_counters_total{node_name=~\"$node_name\"}[$interval]) or irate(mongodb_op_counters_total{node_name=~\"$node_name\"}[5m]))",
     "legendFormat": "{{ kubernetes_pod_name }} - {{type}}"
    }
   ]
  },
  {
   "title": "Max Member Ping Time ",
   "type": "timeseries",
   "description": "This metric can show a correlation with the replication lag value.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max by (node_name, name) (mongodb_mongod_replset_member_ping_ms{set=~\"$replset\"})",
     "legendFormat": "{{node_name}} -> {{name}}"
    }
   ]
  },
  { "title": "Oplog Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "Oplog Buffered Operations",
   "type": "timeseries",
   "description": "Repl buffer ops applied per sec.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (node_name) (mongodb_mongod_metrics_repl_buffer_count{app_kubernetes_io_instance=~\"$replset_instance\"})",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Oplog Getmore Time",
   "type": "timeseries",
   "description": "Time spent per second waiting for or fetching oplog docs in replication.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (node_name) (rate(mongodb_mongod_metrics_repl_network_getmores_total_milliseconds{app_kubernetes_io_instance=~\"$replset_instance\"}[$interval]) or irate(mongodb_mongod_metrics_repl_network_getmores_total_milliseconds{app_kubernetes_io_instance=~\"$replset_instance\"}[5m]))",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Oplog Recovery Window (!)",
   "type": "timeseries",
   "description": "Timespan 'window' between newest and the oldest op in the Oplog collection.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 96 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time()-avg by (node_name) (mongodb_mongod_replset_oplog_tail_timestamp{node_name=~\"$node_name\"})",
     "legendFormat": "Now to End"
    },
    {
     "expr": "avg by (node_name) (mongodb_mongod_replset_oplog_head_timestamp{node_name=~\"$node_name\"}-mongodb_mongod_replset_oplog_tail_timestamp{node_name=~\"$node_name\"})",
     "legendFormat": "Oplog Range"
    }
   ]
  },
  {
   "title": "Oplog Buffer Capacity",
   "type": "timeseries",
   "description": "Current hard-coded max and actual size of repl batch buffer.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 96 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (node_name) (mongodb_mongod_metrics_repl_buffer_size_bytes{node_name=~\"$node_name\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "avg by (node_name) (mongodb_mongod_metrics_repl_buffer_max_size_bytes{node_name=~\"$node_name\"})",
     "legendFormat": "Max"
    }
   ]
  }
 ]
}